language: node_js
node_js: '6'
install: npm install
script:
  - npm run test
  - npm run production
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < doc/coverage/report-lcov/lcov.info
addons:
  code_climate:
    repo_token: 0b04ca0bec968964cbdfda33bdbe5314e97150d0faa2dea54c3aa4dfe96731ea
branches:
  only:
    - master
deploy:
  provider: npm
  email: 'info@crazysquirrel.ru'
  api_key: '443206b0-d7ea-47eb-89ca-9ff2e6ec246b'
  skip_cleanup: true
  on:
    branch: master
